// Tất cả text tiếng Việt cố định — tránh lỗi encode qua GitHub API
export const VI = {
  // Menu
  menu: {
    trangChu: 'Trang chủ',
    gioiThieu: 'Giới thiệu',
    nganhHang: 'Ngành hàng',
    sanPham: 'Sản phẩm',
    duAnTieuBieu: 'Dự án tiêu biểu',
    baoGia: 'Báo giá',
    quyTrinh: 'Quy trình',
    blog: 'Blog',
    lienHe: 'Liên hệ',
    baoGiaNgay: 'Báo Giá Ngay',
    // Dropdown ngành hàng
    tpcnDuocPham: 'TPCN & dược phẩm',
    myPhamSkincare: 'Mỹ phẩm & skincare',
    yenSao: 'Yến sào',
    trangSucQuaTang: 'Trang sức & quà tặng',
    ecommerce: 'Ecommerce',
    // Dropdown sản phẩm — khớp với category slug thật trong WordPress
    catalogue: 'Catalogue',
    tuiGiay: 'Túi giấy',
    hopGiay: 'Hộp giấy',
    hopCung: 'Hộp cứng',
    hopSong: 'Hộp sóng',
    hopQuaTet: 'Hộp quà tết',
    hopTrungThu: 'Hộp trung thu',
  },
  // Page chủ - sections
  dichVu: 'DỊCH VỤ IN ẤN',
  dichVuTitle: 'DỊCH VỤ IN ẤN CHUYÊN NGHIỆP',
  quyTrinh: 'QUY TRÌNH LÀM VIỆC',
  duAnTieuBieu: 'DỰ ÁN TIÊU BIỂU',
  sanPhamDaThucHien: 'SẢN PHẨM ĐÃ THỰC HIỆN',
  xemTatCaDuAn: 'Xem tất cả dự án',
  doiTac: 'ĐỐI TÁC',
  khachHangCuaChungToi: 'KHÁCH HÀNG CỦA CHÚNG TÔI',
  nangLucSanXuat: 'NĂNG LỰC SẢN XUẤT',
  mayMocCongNghe: 'MÁY MÓC & CÔNG NGHỆ',
  chatLuongHangDau: 'Chất lượng hàng đầu · Công nghệ tiên phong · Dịch vụ chuyên nghiệp · In ấn mọi lúc mọi nơi',
  lyDoChon: 'LÝ DO CHỌN CHÚNG TÔI',
  taiSaoChon: 'TẠI SAO CHỌN IN HOÀNG THỊNH?',
  videoGioiThieu: 'VIDEO GIỚI THIỆU',
  thamQuanXuong: 'THAM QUAN XƯỞNG IN',
  tinTuc: 'Tin tức',
  baiVietMoiNhat: 'BÀI VIẾT MỚI NHẤT',
  xemTatCaBaiViet: 'Xem tất cả bài viết',
  khachHangNoiGi: 'KHÁCH HÀNG NÓI GÌ',
  danhGiaTuDoiTac: 'ĐÁNH GIÁ TỪ ĐỐI TÁC',
  nhanBaoGia: 'Nhận Báo Giá Trong 5 Phút',
  nhanBaoGiaDesc: 'Để lại thông tin, chuyên viên của chúng tôi sẽ liên hệ tư vấn và báo giá chi tiết ngay lập tức.',
  // Fallback services
  s1Title: 'In Hộp Cứng Chuyên Nghiệp',
  s1Desc: 'Hộp cứng cao cấp · Ép kim · Đóng gáy sang trọng',
  s2Title: 'In Túi Giấy',
  s2Desc: 'Túi giấy cao cấp Ivory · Couche · Kraft',
  s3Title: 'Bao Bì Mỹ Phẩm',
  s3Desc: 'Bảo vệ tính chất · Ép kim cao cấp',
  s4Title: 'Bao Bì Dược Phẩm',
  s4Desc: 'Bảo quản thuốc · Chuẩn y tế',
  s5Title: 'In Sách - Sổ Tay',
  s5Desc: 'Bìa cứng · Bìa mềm · Đóng gáy',
  s6Title: 'In Nhãn - Tem Decal',
  s6Desc: 'Tem decal · Tem vỡ · Kraft',
  s7Title: 'Bao Bì Nông Sản',
  s7Desc: 'Chuẩn xuất khẩu · Độ bền cao',
  s8Title: 'Thiết Kế Đồ Họa',
  s8Desc: 'Cập nhật xu hướng thiết kế',
  lienHe: 'Liên hệ',
  // Features
  f1Title: 'Máy Ép Kim Tại Xưởng',
  f1Desc: 'In và ép kim ngay trong cùng xưởng. Không gửi ngoài, không outsource. Kiểm soát chất lượng từ đầu đến cuối.',
  f2Title: 'Chủ Xưởng QC Trực Tiếp',
  f2Desc: 'Không phải NV QC — chính chủ xưởng kiểm tra từng lô hàng trước khi giao. 17 năm vẫn giữ nguyên nguyên tắc này.',
  f3Title: 'Sai Màu = In Lại Miễn Phí',
  f3Desc: 'Cam kết bằng hợp đồng. Không đạt yêu cầu về màu sắc — in lại toàn bộ, miễn phí.',
  f4Title: 'MOQ 500 — Nhận Đơn Vừa',
  f4Desc: 'Xưởng lớn từ chối đơn nhỏ. In Hoàng Thịnh nhận từ 500 sản phẩm. Startup hay doanh nghiệp lớn — đều phục vụ.',
  // Process
  p1: 'Tiếp nhận', p2: 'Tư vấn & Báo giá', p3: 'Thiết kế 3D', p4: 'In mẫu test',
  p5: 'Ký hợp đồng', p6: 'Sản xuất hàng loạt', p7: 'Kiểm tra QC', p8: 'Giao hàng',
  // Machines
  m1: 'Máy In Offset', m1d: 'In 4 màu CMYK, chuẩn quốc tế. Công suất cao.',
  m2: 'Máy Ép Kim Vàng', m2d: 'Ép foil vàng, bạc, rose gold. Máy tại xưởng.',
  m3: 'Máy Cán Màng', m3d: 'Cán mờ, cán bóng. Bảo vệ bề mặt, tăng độ sang trọng.',
  m4: 'Máy Bế Tự Động', m4d: 'Bế hình chính xác. Đường cắt sắc nét, không bavia.',
  m5: 'Máy Dán Hộp', m5d: 'Dán cạnh, dán đáy tự động. Năng suất cao, đều đẹp.',
  m6: 'Khu Kiểm Tra QC', m6d: 'Bảng Pantone chuẩn. Chủ xưởng kiểm tra trực tiếp.',
  // Testimonials fallback
  t1c: 'Chúng tôi rất hài lòng với chất lượng hộp cứng ép kim của In Hoàng Thịnh. Màu sắc in chuẩn xác, giao hàng đúng hẹn.',
  t1a: 'Nguyễn Văn A', t1p: 'Giám đốc Marketing - Công ty ABC',
  t2c: 'Đội ngũ tư vấn nhiệt tình, xưởng sản xuất trực tiếp nên giá thành rất cạnh tranh. Đối tác tin cậy 5 năm qua.',
  t2a: 'Trần Thị B', t2p: 'Quản lý thu mua - Tập đoàn G-Group',
  t3c: 'Sản phẩm in mẫu test rất nhanh, giống hệt hàng sản xuất hàng loạt. Hoàng Thịnh xử lý đơn khó rất chuyên nghiệp.',
  t3a: 'Lê Văn C', t3p: 'CEO - Startup PASHANCHA',
  // Popup
  popupTitle: 'Ưu đãi hôm nay',
  popupHeading: 'Thiết kế 3D miễn phí',
  popupDesc: 'Nhận báo giá & thiết kế mẫu 3D miễn phí cho đơn hàng đầu tiên. Liên hệ ngay!',
  // SEO
  seoTitle: 'In Hoàng Thịnh — Giải Pháp Bao Bì Toàn Diện',
  seoDesc: 'Xưởng in bao bì Hà Nội. Hộp cứng, túi giấy, hộp carton, tem nhãn. Cam kết chất lượng, đúng tiến độ, giá gốc tại xưởng.',
};
